# The color configuration is pretty basic
#
# For normal text, rfm uses the foreground and background color of your terminal.
# Apart from that, there are only four colors in use, which can be configured to any
# of the 16 base colors, that are available for all terminals.
#
# Available options are:
# 
# black    , dark-red, dark-green, dark-yellow, dark-blue, dark-magenta, dark-cyan, grey
# dark-grey,      red,      green,      yellow,      blue,      magenta,      cyan, white
#
#

# the 'main' color is used for things like the borders, directory names, and the cursor
main = "dark-green"

# color of 'marked' items
marked = "dark-yellow"

# the 'highlight' color is used to highlight search results, or in the creation of new items
highlight = "red"

# color of the top-row directory path
dir_path = "dark-blue"
