# Basic configuration of rfm
#
# The syntax is pretty simple:
#
# [category]
# command = [ "k" , "sk", "thirdkeybinding" ]
#    ^        ^^^   ^^^^   ^^^^^^^^^^^^^^^^^
#    |      single   |       or even words (without spaces)
#    |       key   multiple
#    |              keys
#    |
# Name of the command
#
# You can specify modifiers for single-key patterns, by using the prefixes
# ctrl-X (for control-key + X)
# alt-X  (for alt-key     + X)
# meta-X (for meta-key    + X)
# Where X can be any key you like ofc.

[general]
search        = [ "/", "search", "f" ]
mark          = [ " " ]
next          = [ "n" ]
previous      = [ "N" ]
view_trash    = [ "gT" ]
toggle_hidden = [ "zh" ]
quit          = [ "q", "Q", "exit" ]
# Use this, if you want to quit without changing directories if --choose-dir is specified:
# quit_no_cd    = [ "alt+q" ]

[movement]
up                 = [ "k" ]
down               = [ "j" ]
left               = [ "h" ]
right              = [ "l" ]
top                = [ "gg" ]
bottom             = [ "G" ]
page_forward       = [ "ctrl-f" ]
page_backward      = [ "ctrl-b" ]
half_page_forward  = [ "ctrl-d" ]
half_page_backward = [ "ctrl-u" ]
jump_previous      = [ "''" ]
#
# You can define custom jumpmarks.
#
# On the left side, you put the keybinding or key-combination,
# and on the right side, the directory you want to jump into.
# You can use "~" for "$HOME".
#
jump_to = [ ["gh", "~"],
            ["gc", "~/.config"],
            ["gp", "~/Pictures"],
            ["gd", "~/Documents"],
            ["gD", "~/Downloads"],
            ["gm", "~/Music"],
            ["gr", "/"],
            ["ge", "/etc"],
            ["gu", "/usr"]]

[manipulation]
change_directory = [ "cd" ]
rename           = [ "rename" ]
mkdir            = [ "mkdir" ]
touch            = [ "touch" ]
cut              = [ "cut", "dd", "ctrl-x" ]
copy             = [ "copy", "yy", "ctrl-c" ]
delete           = [ "delete" ]
paste            = [ "paste", "pp", "ctrl-v" ]
paste_overwrite  = [ "po", "ctrl-V" ]
zip              = [ "zip" ]
tar              = [ "tar" ]
extract          = [ "extract", "unzip" ]
