# Configuration of how to open files with rfm
#
# The file is split into sections of different mime-types like "test" or "application".
# You can set a default application for each mime-type, with the "default" key:
#
# default = { name = "vim", args = [], terminal = true }
#
# The right sight consists of the following keys:
# {
#   name = "vim",    # Name of the application to open
#   args = ["-d"],   # Addition cmdline arguments
#   terminal = true  # If terminal = false, an additional window is spawned and rfm execution continues.
# }                  # if terminal = true, the application is launched inside the current session as a child process
#
#
# If you want to use multiple applications for the same mime-type you can can define them
# with the "extensions" key of the section:
#
# extensions = [ 
#   ["pdf",   { name = "zathura",     args = [], terminal = false } ], 
#   ["ppt",   { name = "libreoffice", args = [], terminal = false } ] 
# ]
#
# The right side is just a list of elements with the same syntax that we used for the "default" key.
#
# If you are not sure what mime-type of a specific file is, you can look at the bottom line of "rfm".
# It shows the mime-type for the current selection.
#

# --- Uncomment to configure mime-type 'text'
#[text]
#default = { name = "nvim", args = [], terminal = true }

# --- Uncomment to configure mime-type 'image'
#[image]
#default = { name = "sxiv", args = [], terminal = true }

# --- Uncomment to configure mime-type 'audio'
#[audio]
#default = { name = "mpv", args = [], terminal = true }

# --- Uncomment to configure mime-type 'video'
#[video]
#default = { name = "mpv", args = [], terminal = true }

# --- Uncomment to configure mime-type 'application'
#[application]
#default = { name = "nvim", args = [], terminal = true }
#extensions = [ 
#  ["pdf",   { name = "zathura",     args = [], terminal = false } ], 
#  ["docx",  { name = "libreoffice", args = [], terminal = false } ],
#  ["xlsx",  { name = "libreoffice", args = [], terminal = false } ],
#  ["xls",   { name = "libreoffice", args = [], terminal = false } ],
#  ["pptx",  { name = "libreoffice", args = [], terminal = false } ],
#  ["ppt",   { name = "libreoffice", args = [], terminal = false } ] 
#]
